import = ["~/.config/alacritty/themes/themes/terminal_app.toml"]

live_config_reload = true

[window]
startup_mode = "Maximized"
option_as_alt = "OnlyLeft"

[font]
size = 13

[font.normal]
family = "JetBrainsMono Nerd Font"
