import = ["~/.config/alacritty/themes/themes/terminal_app.toml"]

live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
startup_mode = "Maximized"

[font]
size = 12

[font.normal]
family = "JetBrainsMono Nerd Font"
